services:
  hhvm:
    container_name: theodore-html-stream-namespaced-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 48561:10641
